### ISSUE TITLE
[Feature Request] Loot Calculator

### ISSUE THREAD

**Issue by VeyezX** [Frixs/BlackSpiritHelper#40]
Loot calculator with timer

Like that you can turn on 1 hour timer, grind for an hour, and it will show how much trash you got, silver, blackstars, etc etc,

Would be a great tool to use for stats and stuff.

**Comment by Frixs** [comment]
Hello,

thank you for your feedback! 
However, this is a very specific feature for BDO while the app can be used for any other games too. It would require a dedicated team managing the app and sync all the items from the entire game to the app database. 

It is definitely a very great thing to have, but there is no need to implement it for BDO because the game already has exactly what you are asking for. The only issue is, it is currently on GlobalLab, not in EU/NA region servers. Hopefully, we will get the feature with the upcoming publisher change. :-)
